language: node_js
node_js:
  - "5"
before_script:
  - npm install
script: npm test
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/a3509f74f21814b4f5d7
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always